spring:
  # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xboot-study?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ENC(TXtXZCpA4YFUZJDPjjp8QQ==)
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    logSlowSql: true


jasypt:
  encryptor:
    password: xboot